package com.yandex.daggerlite.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.FileCollection
import org.gradle.api.file.RegularFile
import org.gradle.api.model.ObjectFactory
import org.gradle.api.provider.Provider
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.kotlin.dsl.getValue
import org.gradle.kotlin.dsl.property
import org.gradle.kotlin.dsl.setValue
import javax.inject.Inject

/**
 * Generates Kotlin source, that contains declarations of a top-level const property with the given name and
 * given classpath value.
 *
 * Classpath is a list of files joined with ':' into a single string.
 */
abstract class ClasspathSourceGeneratorTask @Inject constructor(
    objects: ObjectFactory,
) : DefaultTask() {
    @get:Input
    var packageName: String by objects.property()

    @get:Input
    var propertyName: String by objects.property()

    @get:InputFiles
    var classpath: FileCollection by objects.property()

    @get:OutputFile
    var generatedSource: Provider<RegularFile> by objects.property()

    @TaskAction
    fun action() {
        generatedSource.get().asFile.writeText("""
// This source is GENERATED by gradle task `$name`. Do not edit!

package $packageName

const val $propertyName = "${classpath.joinToString(separator = ":\" +\n\"")}"
""")
    }
}